-- 000_bible_books_seed.sql — 66-book Protestant canon (run BEFORE 001)
-- Idempotent: unique abbreviation + ON CONFLICT DO NOTHING.

CREATE UNIQUE INDEX IF NOT EXISTS bible_books_abbrev_uidx ON public.bible_books(abbreviation);

INSERT INTO public.bible_books (name, abbreviation, testament, book_order, is_canonical) VALUES
  ('Genesis','Gen','old',1,true),
  ('Exodus','Exod','old',2,true),
  ('Leviticus','Lev','old',3,true),
  ('Numbers','Num','old',4,true),
  ('Deuteronomy','Deut','old',5,true),
  ('Joshua','Josh','old',6,true),
  ('Judges','Judg','old',7,true),
  ('Ruth','Ruth','old',8,true),
  ('1 Samuel','1Sam','old',9,true),
  ('2 Samuel','2Sam','old',10,true),
  ('1 Kings','1Kgs','old',11,true),
  ('2 Kings','2Kgs','old',12,true),
  ('1 Chronicles','1Chr','old',13,true),
  ('2 Chronicles','2Chr','old',14,true),
  ('Ezra','Ezra','old',15,true),
  ('Nehemiah','Neh','old',16,true),
  ('Esther','Esth','old',17,true),
  ('Job','Job','old',18,true),
  ('Psalms','Ps','old',19,true),
  ('Proverbs','Prov','old',20,true),
  ('Ecclesiastes','Eccl','old',21,true),
  ('Song of Solomon','Song','old',22,true),
  ('Isaiah','Isa','old',23,true),
  ('Jeremiah','Jer','old',24,true),
  ('Lamentations','Lam','old',25,true),
  ('Ezekiel','Ezek','old',26,true),
  ('Daniel','Dan','old',27,true),
  ('Hosea','Hos','old',28,true),
  ('Joel','Joel','old',29,true),
  ('Amos','Amos','old',30,true),
  ('Obadiah','Obad','old',31,true),
  ('Jonah','Jonah','old',32,true),
  ('Micah','Mic','old',33,true),
  ('Nahum','Nah','old',34,true),
  ('Habakkuk','Hab','old',35,true),
  ('Zephaniah','Zeph','old',36,true),
  ('Haggai','Hag','old',37,true),
  ('Zechariah','Zech','old',38,true),
  ('Malachi','Mal','old',39,true),
  ('Matthew','Matt','new',40,true),
  ('Mark','Mark','new',41,true),
  ('Luke','Luke','new',42,true),
  ('John','John','new',43,true),
  ('Acts','Acts','new',44,true),
  ('Romans','Rom','new',45,true),
  ('1 Corinthians','1Cor','new',46,true),
  ('2 Corinthians','2Cor','new',47,true),
  ('Galatians','Gal','new',48,true),
  ('Ephesians','Eph','new',49,true),
  ('Philippians','Phil','new',50,true),
  ('Colossians','Col','new',51,true),
  ('1 Thessalonians','1Thess','new',52,true),
  ('2 Thessalonians','2Thess','new',53,true),
  ('1 Timothy','1Tim','new',54,true),
  ('2 Timothy','2Tim','new',55,true),
  ('Titus','Titus','new',56,true),
  ('Philemon','Phlm','new',57,true),
  ('Hebrews','Heb','new',58,true),
  ('James','Jas','new',59,true),
  ('1 Peter','1Pet','new',60,true),
  ('2 Peter','2Pet','new',61,true),
  ('1 John','1John','new',62,true),
  ('2 John','2John','new',63,true),
  ('3 John','3John','new',64,true),
  ('Jude','Jude','new',65,true),
  ('Revelation','Rev','new',66,true)
ON CONFLICT (abbreviation) DO NOTHING;
